import React, { useState } from "react";
import Head from "next/head";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import CryptoJS from "crypto-js";
import Typography from "@mui/material/Typography";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [value, setValue] = useState("");
  const [d, setd] = useState("");
  const handleDecrypt = () => {
    const a = value && CryptoJS.AES.decrypt(value, "Zilo");
    console.log(a);
    const b = a && JSON.parse(a?.toString(CryptoJS.enc.Utf8));
    setd(b);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <h1 className={styles.title}>Decode JWT</h1>
            <Box>
              <TextField
                required
                value={value}
                id="outlined-required"
                label="Encrypted key"
                onChange={(e) => setValue(e.target.value)}
              />
            </Box>
            <Box>
              <Button variant="contained" onClick={() => handleDecrypt()}>
                Decode
              </Button>
            </Box>

            {d && (
              <Grid item xs>
                <Typography>{d}</Typography>
              </Grid>
            )}
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
